remove previous t2 kernels but preserve current version
AdityaGarg8/mbp-16.x-ubuntu-kernel pull request #22
Opened 2022-09-28 20:08 UTC by lemmyg

Updated the remove kernels logic to list current kernels and purge old t2 kernels but preserving current kernel as a backup.
This is useful in case there is any bug in any t2 drivers that could prevent the user from start the session.

2022-09-29 03:27 UTC, AdityaGarg8 requested changes

2022-09-29 03:27 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +existingK=($(dpkg --list | grep linux-image- | cut -d ' ' -f 2-3 ))
I guess it would be better to leave the generic kernels as well

```bash
existingK=($(dpkg --list | grep linux-image- | grep -v generic | cut -d ' ' -f 2-3 ))
```

2022-09-29 03:27 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
I don't think `if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]` is required now

2022-09-29 06:05 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
I keep it to ensure we only remove T2 kernels. Just in case the use has  additional kernels.

2022-09-29 06:11 UTC, lemmyg commented on t2-kernel-script/usr/bin/update_t2_kernel
> +				dpkg -P linux-headers-$version
Note that I have changed to -P. To ensure the kernels configs get completely purged. Otherways they were listed in dpkg --list command.

2022-09-29 06:20 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +existingK=($(dpkg --list | grep linux-image- | cut -d ' ' -f 2-3 ))
Same here, Im  trying not to touch non T2 kernels.

2022-09-29 06:21 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
Then we can do this check by modifying `existingK` variable instead so that it lists the T2 kernels only.

2022-09-29 06:25 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
So maybe filter the list with a regex expression?

2022-09-29 08:55 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
```bash
existingK=($(dpkg --list | grep 't2\|mbp` | cut -d ' ' -f 2-3 ))
```

Should this be good?

2022-09-29 09:07 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +existingK=($(dpkg --list | grep linux-image- | cut -d ' ' -f 2-3 ))
Yes

2022-09-29 09:10 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
> I keep it to ensure we only remove T2 kernels. Just in case the user has additional kernels.

What this if will do is that, if the kernel you are booting is a T2 kernel, then it will remove all the old T2 kernels. But if the script is run on a non T2/self compiled kernel, then no kernel would be removed.

So it doesn’t make much sense to keep this if statement and we should rather edit the list of kernels to be removed by editing the `existingK` variable.

2022-09-29 09:52 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
```bash
#!/bin/bash
#upgrading script apple linux T2 Kernel

if [ $USER != root ]
then
sudo chmod 755 $0
sudo $0 $1
exit 0
fi

if [[ ($1 != -v) && ($2 != -v) ]]
then
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/log/t2-kernel-update.log 2>&1
fi

set -e

cd /tmp

use_lts=true
lts_version=5.15

if [[ $use_lts != true ]]
then
latest=$(curl -sL https://github.com/t2linux/T2-Ubuntu-Kernel/releases/latest/ | grep "<title>Release" | awk -F " " '{print $2}' )
else
getkernelver=$(curl -sL https://github.com/t2linux/T2-Ubuntu-Kernel/releases | grep "{{ urlEncodedRefName }}" | grep -v "generic" | grep v${lts_version} | cut -d "{" -f 3 | cut -c 25- | head -1)
latest=${getkernelver::-76}
fi

if [[ ${#latest} = 7 ]]
then
latestkver=$(echo $latest | cut -d "v" -f 2 | cut -d "-" -f 1 | awk '{print $1".0-1"}')
latestk=$(echo $latest | cut -c 2- | cut -d "-" -f 1 | awk '{print $1".0-t2"}')
else
latestkver=$(echo $latest | cut -d "v" -f 2)
latestk=$(echo $latest | cut -c 2- | cut -d "-" -f 1 | awk '{print $1"-t2"}')
fi

currentk=$(uname -r)
existingK=($(dpkg --list | grep linux-image- | grep 't2\|mbp' | cut -d ' ' -f 2-3 ))
if [ \( $latestk != $currentk \) ]; then
	
	echo "Downloading new kernel $latest"
	curl -L https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/${latest}/linux-headers-${latestk}_${latestkver}_amd64.deb > headers.deb
	curl -L https://github.com/t2linux/T2-Ubuntu-Kernel/releases/download/${latest}/linux-image-${latestk}_${latestkver}_amd64.deb > image.deb

	if [ -f headers.deb -a -f image.deb ]; then
	#install
	echo "Installing new kernel $latest"
	apt install ./headers.deb
	apt install ./image.deb
	#shutdown -r 02:00 "reboot scheduled for the next 2am to update runnning kernel"
	rm -f headers.deb image.deb

	#uninstall old t2 kernels but preserve current version as a backup
	for kernel in "${existingK[@]}"
	do
		if [ \( $kernel != linux-image-$currentk \) ]; then
			echo "$kernel needs to be removed"
			version=${kernel/#linux-image-}
			#purge old t2 kernel

			dpkg -P linux-headers-$version
			dpkg -P linux-image-$version
		fi

		if [[ ($1 = --remove-current) || ($2 = --remove-current) ]]; then
			echo "Current kernel linux-image-$currentk shall also be removed"

			dpkg -P linux-headers-$currentk
			dpkg -P linux-headers-$currentk
		fi
	done
	fi
else
echo "Kernel is up to date"
fi
```


Probably this could be used, it also has an option if user wants to remove the current kernel as well.

2022-09-29 10:52 UTC, lemmyg commented
Im working now. Ill reply around 22.00 BST

2022-09-29 13:15 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
> 
I think I got a good regex to select only t2 kernels
`dpkg --list | grep -E 'linux-image-[0-9\.-]+-generic' | cut -d ' ' -f 2-3`

2022-09-29 13:18 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
Well I actually wanted it to remove the old kernels which had mbp, mbp-16x-wifi, t2-big-sur etc as well.

2022-09-29 13:19 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
Ubuntu users who are using the T2 ISO for a long time are likely to have this clutter collected.

2022-09-29 13:21 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +existingK=($(dpkg --list | grep linux-image- | cut -d ' ' -f 2-3 ))
`dpkg --list | grep -E 'linux-image-[0-9\.-]+-t2' | cut -d ' ' -f 2-3` work fine to filter t2 kernels

2022-09-29 13:21 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
And the `—remove-current` option is especially for those who want to switch to LTS from Mainline.

2022-09-29 13:35 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
the way I see is that we just care about current t2 kernels.
if the user uses a very old kernel or custom one we don't remove it and we leave the user to resolve it manually.
that will make the script simple.
currentK is just for check if user is using a t2 kernel and keep it.

2022-09-29 13:59 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
Well what I meant was that, the T2 kernels before didn’t have just t2 at the end. Initially they had mbp, then came mbp-16x-wifi, then came t2-big-sur and finally it went to t2. So, I checked for those t2 kernels as well.

So the script checks for those as well and no custom kernel shall be removed.

2022-09-29 14:01 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
90% users are not even aware that they have these kernels installed in their machines. Iirc, a user had 10 old kernels he didn’t know about. So this script is a good way to get those cleaned up.

2022-09-29 14:02 UTC, AdityaGarg8 commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
If I make sense now, could you do the requested changes so that I can close the PR.

2022-09-29 19:38 UTC, lemmyg commented on t2-kernel-script-lts/usr/bin/update_t2_kernel
> +			if [[ $(uname -r | cut -d "-" -f 2) = t2 ]]; then
I got the changes, basically I copied what you pasted. Also I fixed the indentation as it wasn't clear the scope of one the if statement.
Let me know what you think.
thanks

2022-09-29 19:39 UTC, lemmyg commented
I tested the code it works
thanks

2022-09-29 19:44 UTC, lemmyg commented
about -v argument, should not be always on? 
Why a user would like to run this process silently?

2022-09-29 21:09 UTC, AdityaGarg8 commented
> about -v argument, should not be always on?
> Why a user would like to run this process silently?

Well I was thinking to removing it as well. Actually this script originally was meant to run as a monthly script placed in `/etc/cron.monthly`, but later I edited it to be run manually.

2022-09-29 21:09 UTC, AdityaGarg8 commented
If you want, you may cleanup the -v completely.

2022-09-29 21:20 UTC, lemmyg commented
I go for it

2022-09-29 21:24 UTC, lemmyg commented
I can remove all this right?
if [[ ($1 != -v) && ($2 != -v) ]]
then
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/var/log/t2-kernel-update.log 2>&1
fi

2022-09-30 03:16 UTC, AdityaGarg8 approved these changes

2022-09-30 03:16 UTC, AdityaGarg8 commented
Thanks

2022-09-30 03:16 UTC, merged